//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyMetadataOldToNew {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=hdstation.net;uid=sa;pwd=Hd123456!DB;database=HDAdv2017")]
        public string NewDBConnectionString {
            get {
                return ((string)(this["NewDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=(local);uid=sa;pwd=Hd123456!DB;database=TVAD2017")]
        public string OldDBConnectionString {
            get {
                return ((string)(this["OldDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22fff45d-1b5c-4e8a-a15e-7a7853b0158f")]
        public global::System.Guid ContentTypeTVCId {
            get {
                return ((global::System.Guid)(this["ContentTypeTVCId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08dbaa65-e340-4472-94c9-4b453d769453")]
        public global::System.Guid ContentTypeDOCId {
            get {
                return ((global::System.Guid)(this["ContentTypeDOCId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:39647/Workflow/Api/")]
        public string WorkflowAPIAddress {
            get {
                return ((string)(this["WorkflowAPIAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aff1cfd5-3dc1-e711-8458-00155d0a2e00")]
        public global::System.Guid WorkflowDiagramId {
            get {
                return ((global::System.Guid)(this["WorkflowDiagramId"]));
            }
        }
    }
}
